name: ci-gh-action
on: 
    push:
        branches:
            - main
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Running a oneline script
              run: echo "Hello World!"
            - name: running another
              run: echo "Hello World War II"
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y curl jq
                echo "curl: $(curl --version)"
                echo "jq: $(jq --version)"