name: Upload and Download

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name to greet to'
                required: false
                default: 'World'
    push:
        branches:
            -main
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: hello
                  path: hello.txt
            - name: Create file
              run: echo "Hello World" > hello.txt
            - name: File List
              run: ls -a

    download:
        needs: upload
        runs-on: ubuntu-latest
        steps:
            - name: Download
              uses: actions/download-artifact@v4
              with:
                  name: hello
            - name: File List
              run: ls -a
            - name: Display
              run: cat hello.txt